networks:
  astral-net:
    driver: bridge

services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - config/config.env
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_DATABASE"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    networks:
      - astral-net

  redis:
    image: redis:8.0
    container_name: redis
    env_file:
      - config/config.env
    command: sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a REDIS_PASSWORD -p 6379 ping | grep PONG" ]
      timeout: 3s
      retries: 5
    networks:
      - astral-net